### ISSUE TITLE
Plugin does not work anymore: handshake failure

### ISSUE THREAD

**Issue by rzepkamichal** [File5/intellij-idea-guidesigner-plugin#4]
I get a handshake failure when I try to compile the project:

Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.jetbrains.intellij.java:java-gui-forms-rt:+.
     Required by:
         project :
      > Failed to list versions for com.jetbrains.intellij.java:java-gui-forms-rt.
         > Unable to load Maven meta-data from https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-gui-forms-rt/maven-metadata.xml.
            > Could not get resource 'https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-gui-forms-rt/maven-metadata.xml'.
               > Could not GET 'https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-gui-forms-rt/maven-metadata.xml'.
                  > Received fatal alert: handshake_failure
      > Failed to list versions for com.jetbrains.intellij.java:java-gui-forms-rt.
         > Unable to load Maven meta-data from https://cache-redirector.jetbrains.com/intellij-dependencies/com/jetbrains/intellij/java/java-gui-forms-rt/maven-metadata.xml.
            > Could not get resource 'https://cache-redirector.jetbrains.com/intellij-dependencies/com/jetbrains/intellij/java/java-gui-forms-rt/maven-metadata.xml'.
               > Could not GET 'https://cache-redirector.jetbrains.com/intellij-dependencies/com/jetbrains/intellij/java/java-gui-forms-rt/maven-metadata.xml'.
                  > Received fatal alert: handshake_failure

**Comment by File5** [comment]
Hello!
I've finally got to test this but for me everything seems to work.
I tried deleting `~/.gradle/cache` and running build again and the download works without problems.

It seems like there was some random network issue between you and JetBrains server.

Can you try deleting Gradle cache and trying again?

I think it worth trying again because JetBrains seems to use CloudFront, so it dynamically updates the path to server sometimes.
And also, the file in your error (https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/java/java-gui-forms-rt/maven-metadata.xml), the link seems to be valid and I can download it even with the browser, SSL seems to be valid too.
There is the line in the file which suggest it was updated on Nov 8th, 2022:
```
<lastUpdated>20221108154450</lastUpdated>
```
So, unfortunately, I don't see any other options rather than cleaning Gradle cache, using newer Gradle version (I'm using 7.1) and checking your network connection (try disabling VPN if you're using it).

Feel free to let me know if it's working for you!
